# Go get mbasic80 from the 'net

all:: mbasic.com

TOP=../../..
include $(TOP)/Make.default
include $(TOP)/Make.rules

mbasic.com:
	wget -O mbasic.com http://www.retroarchive.org/cpm/lang/Mbasic.com


